export interface JepoardyGame {
  currentState: number;
  states: JepoardyGameState[];
}

export interface JepoardyGameState {
  admin: JepoardyAdmin;
  players: JepoardyPlayer[];
  boards: Board[];
  currentBoard: Board;
  currentQuestion: Question;
  currentPlayer: number;
  currentRandomQuestions: Question[];
  buzzerQueue: string[];
  password: string;
  state: "START" | "BOARD" | "QUESTION" | "RANDOMQUESTION";
}

export interface JepoardyAdmin {
  name: string;
  vdoNinjaLink: string;
}

export interface JepoardyPlayer {
  name: string;
  points: number;
  vdoNinjaLink: string;
  turn: boolean;
  buzzed: boolean;
  yoinkJoker: boolean;
  noYouJoker: boolean;
  gmJoker: number;
}

export interface Board {
  id: number;
  categories: Category[];
  extra: "default" | "forced" | "DREHDASRAD"; // das ist so cheaten haha this is going to backfire 100%
}

export interface Category {
  name: string;
  extra: "default" | "forced";
  questions: Question[][];
}

export interface Question {
  id: number;
  category: string;
  points: number;
  type: "AUDIO" | "IMAGE" | "TEXT" | "VIDEO";
  extra:
    | "Active"
    | "Taunt"
    | "Windfury"
    | "Gold"
    | "Inactive"
    | "Safezone"
    | "Corrupted";
  question: string;
  answertype: "VIDEO" | "TEXT" | "IMAGE";
  answer: string;
  state: "PAUSED" | "INVISIBLE" | "ACTIVE";
  finished: boolean;
  buzzedPlayers: JepoardyPlayer[];
  info?: string;
  joker?: string;
}

export interface JepoardyGameProps {
  gamestate: JepoardyGameState;
  sendState: (newState: JepoardyGameState) => void;
  clearBuzzer: () => void;
  clearOneBuzzer: (buzzer: string) => void;
  buzzerQueue: string[];
}

export interface JepoardyQuestionProps {
  questions: Question[];
  sendState: (newState: JepoardyGameState) => void;
  gamestate: JepoardyGameState;
}

export interface JepoardySingleQuestionProps {
  question: Question;
  sendState: (newState: JepoardyGameState) => void;
  gamestate: JepoardyGameState;
}

export const TESTGamestate: JepoardyGameState = {
  password: "test",
  admin: {
    name: "Autophil",
    vdoNinjaLink: "https://vdo.ninja/?view=HqEPyCb",
  },
  currentPlayer: 1,
  players: [
    {
      name: "Krokoboss",
      points: 0,
      vdoNinjaLink: "https://vdo.ninja/?view=HqEPyCb",
      turn: false,
      buzzed: false,
      yoinkJoker: false,
      noYouJoker: false,
      gmJoker: -1,
    },
    {
      name: "Kutcher",
      points: 0,
      vdoNinjaLink: "https://vdo.ninja/?view=HqEPyCb",
      turn: false,
      buzzed: false,
      yoinkJoker: false,
      noYouJoker: false,
      gmJoker: -1,
    },
    {
      name: "Broeki",
      points: 0,
      vdoNinjaLink: "https://vdo.ninja/?view=HqEPyCb",
      turn: false,
      buzzed: false,
      yoinkJoker: false,
      noYouJoker: false,
      gmJoker: -1,
    },
    {
      name: "TwoStone",
      points: 0,
      vdoNinjaLink: "https://vdo.ninja/?view=HqEPyCb",
      turn: false,
      buzzed: false,
      yoinkJoker: false,
      noYouJoker: false,
      gmJoker: -1,
    },
  ],
  state: "BOARD",
  currentBoard: {
    id: 1,
    extra: "default",
    categories: [
      {
        name: "Finanzamt kommt",
        extra: "default",
        questions: [
          [
            {
              id: 0,
              category: "Finanzamt kommt",
              points: 200,
              type: "IMAGE",
              extra: "Active",
              question: "1700_-200.png",
              answertype: "TEXT",
              state: "ACTIVE",
              answer: "1700G",
              finished: false,
              buzzedPlayers: [],
              info: "400 + (2*50) +  1200 = 1700",
            },
          ],
          [
            {
              id: 1,
              category: "Finanzamt kommt",
              points: 400,
              type: "IMAGE",
              extra: "Active",
              question: "4500_-_400.png",
              answertype: "TEXT",
              state: "ACTIVE",
              answer: "4500G",
              finished: false,
              buzzedPlayers: [],
              info: "450 + 3100 + 875 + 75 = 4500",
            },
          ],
          [
            {
              id: 2,
              category: "Finanzamt kommt",
              points: 600,
              type: "IMAGE",
              extra: "Active",
              question: "6850_-_600.png",
              answertype: "TEXT",
              state: "ACTIVE",
              answer: "6850G",
              finished: false,
              buzzedPlayers: [],
              info: "3000 + 1250 + 1200 + 1050 + 350 = 6850",
            },
          ],
          [
            {
              id: 3,
              category: "Finanzamt kommt",
              points: 800,
              type: "IMAGE",
              extra: "Active",
              question: "5030_-_800.png",
              answertype: "TEXT",
              state: "ACTIVE",
              answer: "5030G",
              finished: false,
              buzzedPlayers: [],
              info: "400 + 900 + 600 + 850 + 2200 + (2*40) = 5030",
            },
          ],
          [
            {
              id: 4,
              category: "Finanzamt kommt",
              points: 1000,
              type: "IMAGE",
              extra: "Active",
              question: "2937_-1000.png",
              answertype: "TEXT",
              state: "ACTIVE",
              answer: "2937G",
              finished: false,
              buzzedPlayers: [],
              info: "1337 + 1100 + 150 + 350 = 2937",
            },
          ],
        ],
      },
      {
        name: "Community",
        extra: "default",
        questions: [
          [
            {
              id: 5,
              category: "Community",
              points: 600,
              type: "TEXT",
              state: "ACTIVE",
              extra: "Active",
              question: "Welchen Champ bannst du immer?",
              answertype: "TEXT",
              answer: "Shaco, Mel, Zed",
              finished: false,
              buzzedPlayers: [],
              info: "Shaco: 26, Mel: 16, Zed: 13, Pyke: 12, Fizz: 12, Yasuo: 11, unklar/je nachdem: 10",
            },
          ],
          [
            {
              id: 6,
              category: "Community",
              points: 600,
              type: "TEXT",
              state: "ACTIVE",
              extra: "Active",
              question: "Welchen Champ hast du am liebsten im eigenen Team?",
              answertype: "TEXT",
              answer: "Ornn, Shen, Lulu",
              finished: false,
              buzzedPlayers: [],
              info: "Ornn: 30, Shen: 17, Lulu: 17, Nautilus: 15, Egal/Unklar: 15, Braum: 13, Thresh: 10, Malphite: 10",
            },
          ],
          [
            {
              id: 7,
              category: "Community",
              points: 600,
              type: "TEXT",
              state: "ACTIVE",
              extra: "Active",
              question: "Spielst du mit Flash auf D oder Flash auf F?",
              answertype: "TEXT",
              answer: "D",
              finished: false,
              buzzedPlayers: [],
              info: "Flash auf D: 151, Flash auf F: 141",
            },
          ],
          [
            {
              id: 8,
              category: "Community",
              points: 600,
              type: "TEXT",
              state: "ACTIVE",
              extra: "Active",
              question: "Was ist das beste Emote in League?",
              answertype: "TEXT",
              answer: "OK, Unklar/Keins, Daumen hoch",
              finished: false,
              buzzedPlayers: [],
              info: "OK/'Okay' (Rammus): 114, Unklar/Keins: 40, Daumen hoch/Thumbs Up ('Nice'): 35, Dabbing Pengu (D'Pengu): 21, Bee Happy: 20",
            },
          ],
          [
            {
              id: 9,
              category: "Community",
              points: 600,
              type: "TEXT",
              state: "ACTIVE",
              extra: "Active",
              question:
                "Was ist dein Lieblingsitem? (was momentan im Shop zu finden ist)",
              answertype: "TEXT",
              answer: "Heartsteel, Rabadons Deathcap, Infinity Edge",
              finished: false,
              buzzedPlayers: [],
              info: "Heartsteel: 26, Rabadons Deathcap: 26, Infinity Edge: 17, Blade of the Ruined King: 15, Shadowflame: 13, Unklar/Keins: 12",
            },
          ],
        ],
      },
      {
        name: "Streamers Liebling",
        extra: "default",
        questions: [
          [
            {
              id: 10,
              category: "Streamers Liebling",
              points: 200,
              type: "VIDEO",
              state: "INVISIBLE",
              extra: "Active",
              question: "BigSpin_Irelia.mp4",
              answertype: "TEXT",
              answer: "Irelia",
              finished: false,
              buzzedPlayers: [],
            },
          ],
          [
            {
              id: 11,
              category: "Streamers Liebling",
              points: 400,
              type: "VIDEO",
              state: "INVISIBLE",
              extra: "Active",
              question: "Mango_Mordekaiser.mp4",
              answertype: "TEXT",
              answer: "Mordekaiser",
              finished: false,
              buzzedPlayers: [],
            },
          ],
          [
            {
              id: 12,
              category: "Streamers Liebling",
              points: 600,
              type: "VIDEO",
              state: "INVISIBLE",
              extra: "Active",
              question: "Mango_Mordekaiser.mp4",
              answertype: "TEXT",
              answer: "5",
              finished: false,
              buzzedPlayers: [],
            },
          ],
          [
            {
              id: 13,
              category: "Streamers Liebling",
              points: 800,
              type: "VIDEO",
              state: "INVISIBLE",
              extra: "Active",
              question: "Mango_Mordekaiser.mp4",
              answertype: "TEXT",
              answer: "5",
              finished: false,
              buzzedPlayers: [],
            },
          ],
          [
            {
              id: 14,
              category: "Streamers Liebling",
              points: 1000,
              type: "VIDEO",
              state: "INVISIBLE",
              extra: "Active",
              question: "Mango_Mordekaiser.mp4",
              answertype: "TEXT",
              answer: "5",
              finished: false,
              buzzedPlayers: [],
            },
          ],
        ],
      },
      {
        name: "OddOneOut",
        extra: "default",
        questions: [
          [
            {
              id: 15,
              category: "OddOneOut",
              points: 200,
              type: "IMAGE",
              state: "ACTIVE",
              extra: "Active",
              question: "twitch_zaheen_w_auf_r.png",
              answertype: "TEXT",
              answer: "Twitch mit Zaheen W auf R",
              finished: false,
              buzzedPlayers: [],
            },
          ],
          [
            {
              id: 16,
              category: "OddOneOut",
              points: 400,
              type: "IMAGE",
              state: "ACTIVE",
              extra: "Active",
              question: "rell__skarner_e.png",
              answertype: "TEXT",
              answer: "Rell mit Skarner E auf E",
              finished: false,
              buzzedPlayers: [],
            },
          ],
          [
            {
              id: 17,
              category: "OddOneOut",
              points: 600,
              type: "IMAGE",
              state: "ACTIVE",
              extra: "Active",
              question: "kassadin__malz_w.png",
              answertype: "TEXT",
              answer: "Kassadin mit Malzahar E auf E",
              finished: false,
              buzzedPlayers: [],
            },
          ],
          [
            {
              id: 18,
              category: "OddOneOut",
              points: 800,
              type: "IMAGE",
              state: "ACTIVE",
              extra: "Active",
              question: "yasuo__janna_p.png",
              answertype: "TEXT",
              answer: "Yasuo mit Janna Passive auf Passive",
              finished: false,
              buzzedPlayers: [],
            },
          ],
          [
            {
              id: 19,
              category: "OddOneOut",
              points: 1000,
              type: "IMAGE",
              state: "ACTIVE",
              extra: "Active",
              question: "brand__leo_r.png",
              answertype: "TEXT",
              answer: "Brand mit Leona R auf R",
              finished: false,
              buzzedPlayers: [],
            },
          ],
        ],
      },
      {
        name: "Sound Themes",
        extra: "default",
        questions: [
          [
            {
              id: 20,
              category: "Sound Themes",
              points: 200,
              type: "AUDIO",
              state: "INVISIBLE",
              extra: "Active",
              question: "Kaisa.mp3",
              answertype: "TEXT",
              answer: "Kai'sa",
              finished: false,
              buzzedPlayers: [],
            },
          ],
          [
            {
              id: 21,
              category: "Sound Themes",
              points: 400,
              type: "AUDIO",
              state: "INVISIBLE",
              extra: "Active",
              question: "NunuWillump.mp3",
              answertype: "TEXT",
              answer: "Nunu & Willump",
              finished: false,
              buzzedPlayers: [],
            },
          ],
          [
            {
              id: 22,
              category: "Sound Themes",
              points: 600,
              type: "AUDIO",
              state: "INVISIBLE",
              extra: "Active",
              question: "MorgKayle.mp3",
              answertype: "TEXT",
              answer: "Morgana & Kayle",
              finished: false,
              buzzedPlayers: [],
            },
          ],
          [
            {
              id: 23,
              category: "Sound Themes",
              points: 800,
              type: "AUDIO",
              state: "INVISIBLE",
              extra: "Active",
              question: "XayahRakan.mp3",
              answertype: "TEXT",
              answer: "Xayah & Rakan",
              finished: false,
              buzzedPlayers: [],
            },
          ],
          [
            {
              id: 24,
              category: "Sound Themes",
              points: 1000,
              type: "AUDIO",
              state: "INVISIBLE",
              extra: "Active",
              question: "Skarner.mp3",
              answertype: "TEXT",
              answer: "Skarner",
              finished: false,
              buzzedPlayers: [],
            },
          ],
        ],
      },
    ],
  },
  currentRandomQuestions: [
    {
      id: 5,
      category: "Erkennen",
      points: 100,
      type: "TEXT",
      state: "ACTIVE",
      extra: "Active",
      question: "Wie viele Finger zeige ich?",
      answertype: "TEXT",
      answer: "5",
      finished: true,
      buzzedPlayers: [],
    },
  ],
  currentQuestion: {
    id: -1,
    category: "START",
    points: 100,
    type: "TEXT",
    state: "ACTIVE",
    extra: "Active",
    question: "STARTFRAGE",
    answertype: "TEXT",
    answer: "START",
    finished: true,
    buzzedPlayers: [
      {
        name: "Krokoboss",
        points: 0,
        vdoNinjaLink: "https://vdo.ninja/?view=HqEPyCb",
        turn: false,
        buzzed: false,
        yoinkJoker: true,
        noYouJoker: true,
        gmJoker: 1,
      },
    ],
  },
  boards: [
    {
      id: 0,
      extra: "default",
      categories: [
        {
          name: "Guess the Champ",
          extra: "default",
          questions: [
            [
              {
                id: 10,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "LeonaAugen.png",
                answertype: "IMAGE",
                answer: "Leona_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Augen",
              },
              {
                id: 10,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "LeonaBrust.png",
                answertype: "IMAGE",
                answer: "Leona_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Brust",
              },
              {
                id: 10,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "LeonaHand.png",
                answertype: "IMAGE",
                answer: "Leona_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Hand",
              },
              {
                id: 10,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "LeonaHufte.png",
                answertype: "IMAGE",
                answer: "Leona_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Hüfte",
              },
              {
                id: 10,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "LeonaLippen.png",
                answertype: "IMAGE",
                answer: "Leona_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Lippen",
              },
            ],
            [
              {
                id: 11,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "NasusAugen.png",
                answertype: "IMAGE",
                answer: "Nasus_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Augen",
              },
              {
                id: 11,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "NasusBrust.png",
                answertype: "IMAGE",
                answer: "Nasus_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Brust",
              },
              {
                id: 11,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "NasusHand.png",
                answertype: "IMAGE",
                answer: "Nasus_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Hand",
              },
              {
                id: 11,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "NasusHufte.png",
                answertype: "IMAGE",
                answer: "Nasus_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Hüfte",
              },
              {
                id: 11,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "NasusLippen.png",
                answertype: "IMAGE",
                answer: "Nasus_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Lippen",
              },
            ],
            [
              {
                id: 12,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "ShyvanaAugen.png",
                answertype: "IMAGE",
                answer: "Shyvana_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Augen",
              },
              {
                id: 12,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "ShyvanaBrust.png",
                answertype: "IMAGE",
                answer: "Shyvana_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Brust",
              },
              {
                id: 12,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "ShyvanaHand.png",
                answertype: "IMAGE",
                answer: "Shyvana_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Hand",
              },
              {
                id: 12,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "ShyvanaHufte.png",
                answertype: "IMAGE",
                answer: "Shyvana_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Hüfte",
              },
              {
                id: 12,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "ShyvanaLippen.png",
                answertype: "IMAGE",
                answer: "Shyvana_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Lippen",
              },
            ],
            [
              {
                id: 13,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "ViegoAugen.png",
                answertype: "IMAGE",
                answer: "Viego_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Augen",
              },
              {
                id: 13,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "ViegoBrust.png",
                answertype: "IMAGE",
                answer: "Viego_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Brust",
              },
              {
                id: 13,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "ViegoHand.png",
                answertype: "IMAGE",
                answer: "Viego_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Hand",
              },
              {
                id: 13,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "ViegoHufte.png",
                answertype: "IMAGE",
                answer: "Viego_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Hüfte",
              },
              {
                id: 13,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "ViegoLippen.png",
                answertype: "IMAGE",
                answer: "Viego_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Lippen",
              },
            ],
            [
              {
                id: 14,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "ZileanAugen.png",
                answertype: "IMAGE",
                answer: "Zilean_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Augen",
              },
              {
                id: 14,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "ZileanBrust.png",
                answertype: "IMAGE",
                answer: "Zilean_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Brust",
              },
              {
                id: 14,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "ZileanHand.png",
                answertype: "IMAGE",
                answer: "Zilean_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Hand",
              },
              {
                id: 14,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "ZileanHufte.png",
                answertype: "IMAGE",
                answer: "Zilean_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Hüfte",
              },
              {
                id: 14,
                category: "Guess the Champ",
                points: 300,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "ZileanHand.png",
                answertype: "IMAGE",
                answer: "Zilean_0.jpg",
                finished: false,
                buzzedPlayers: [],
                info: "Lippen",
              },
            ],
          ],
        },
        {
          name: "LOL",
          extra: "default",
          questions: [
            [
              {
                id: 5,
                category: "LOL",
                points: 100,
                type: "AUDIO",
                state: "INVISIBLE",
                extra: "Active",
                question: "Sona_Original_Laugh_0.ogg",
                answertype: "TEXT",
                answer: "Sona",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 6,
                category: "LOL",
                points: 200,
                type: "AUDIO",
                state: "INVISIBLE",
                extra: "Active",
                question: "Pyke_Original_Laugh_0.ogg",
                answertype: "TEXT",
                answer: "Pyke",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 7,
                category: "LOL",
                points: 300,
                type: "AUDIO",
                state: "INVISIBLE",
                extra: "Active",
                question: "Taliyah_Original_Laugh_0.ogg",
                answertype: "TEXT",
                answer: "Taliyah",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 8,
                category: "LOL",
                points: 400,
                type: "AUDIO",
                state: "INVISIBLE",
                extra: "Active",
                question: "Quinn_Original_Laugh_0.ogg",
                answertype: "TEXT",
                answer: "Quinn",
                finished: false,
                buzzedPlayers: [],
                joker: "Gamemaster",
              },
            ],
            [
              {
                id: 9,
                category: "LOL",
                points: 500,
                type: "AUDIO",
                state: "INVISIBLE",
                extra: "Active",
                question: "Alistar_Original_Laugh_1.ogg",
                answertype: "TEXT",
                answer: "Alistar",
                finished: false,
                buzzedPlayers: [],
              },
            ],
          ],
        },

        {
          name: "One Sentence Lore",
          extra: "default",
          questions: [
            [
              {
                id: 15,
                category: "One Sentence Lore",
                points: 100,
                type: "TEXT",
                state: "ACTIVE",
                extra: "Active",
                question:
                  "Dieser Champ durchquert die Welt, weil er einen Freund finden will, aber ein Fluch macht es ihm unmöglich",
                answertype: "TEXT",
                answer: "Amumu",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 16,
                category: "One Sentence Lore",
                points: 200,
                type: "TEXT",
                state: "ACTIVE",
                extra: "Active",
                question:
                  "Dieser Champ war eigentlich nur ein Fabelwesen, das Kindern Angst machen sollte, doch wurde real",
                answertype: "TEXT",
                answer: "Fiddlesticks",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 17,
                category: "One Sentence Lore",
                points: 300,
                type: "TEXT",
                state: "ACTIVE",
                extra: "Active",
                question:
                  "Der gesuchte Champ ist laut Lore mit folgenden Champs verknüpft: Ornn, Udyr, Anivia, Volibear",
                answertype: "TEXT",
                answer: "Aurora",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 18,
                category: "One Sentence Lore",
                points: 400,
                type: "TEXT",
                state: "ACTIVE",
                extra: "Active",
                question:
                  "Dieser Champ sollte eine politische Ehe eingehen, weigerte sich und brachte anschließend den eigenen Vater um",
                answertype: "TEXT",
                answer: "Fiora",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 19,
                category: "One Sentence Lore",
                points: 500,
                type: "TEXT",
                state: "ACTIVE",
                extra: "Active",
                question:
                  "Dieser Champ entdeckte die eigenen Fähigkeiten durch Wut und aus dem Wunsch heraus nie wieder kontrolliert zu werden",
                answertype: "TEXT",
                answer: "Syndra",
                finished: false,
                buzzedPlayers: [],
                joker: "NoYou",
              },
            ],
          ],
        },
        {
          name: "Jhin",
          extra: "default",
          questions: [
            [
              {
                id: 20,
                category: "Jhin",
                points: 444,
                type: "TEXT",
                extra: "Active",
                question: "Nenne 4 Champs, die von den Shadow Isles kommen",
                answertype: "TEXT",
                state: "ACTIVE",
                answer:
                  "Elise, Gwen, Hecarim, Kalista, Karthus, Maokai, Thresh, Vex, Viego, Yorick",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 21,
                category: "Jhin",
                points: 444,
                type: "TEXT",
                extra: "Active",
                question: "Nenne 4 Champs mit einer Revive Mechanic",
                answertype: "TEXT",
                state: "ACTIVE",
                answer: "Akshan, Zilean, Renata, Zaahen, Zac, Anivia",
                finished: false,
                buzzedPlayers: [],
                joker: "Yoink",
              },
            ],
            [
              {
                id: 22,
                category: "Jhin",
                points: 444,
                type: "TEXT",
                extra: "Active",
                question: "Nenne 4 Yordle Champs",
                answertype: "TEXT",
                state: "ACTIVE",
                answer:
                  "Corki, Fizz, Gnar, Heimerdinger, Kennen, Kled, Lulu, Poppy, Rumble, Teemo, Tristana, Veigar, Ziggs",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 23,
                category: "Jhin",
                points: 444,
                type: "TEXT",
                extra: "Active",
                question: "Nenne die 4 neusten Champs",
                answertype: "TEXT",
                state: "ACTIVE",
                answer: "Zaahen, Yunara, Mel, Ambessa",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 24,
                category: "Jhin",
                points: 444,
                type: "TEXT",
                extra: "Active",
                question:
                  "Nenne 4 Champs, die im 'Still here' Musikvideo auftreten",
                answertype: "TEXT",
                state: "ACTIVE",
                answer:
                  "Tryndamere, Kindred, Yasuo, Morgana, Kayle, Aatrox, Ashe",
                finished: false,
                buzzedPlayers: [],
              },
            ],
          ],
        },
        {
          name: "Imposter",
          extra: "default",
          questions: [
            [
              {
                id: 25,
                category: "Imposter",
                points: 100,
                type: "TEXT",
                state: "ACTIVE",
                extra: "Active",
                question: `Diese Champs nutzen Mana als Ressource: 
                  Aatrox, Ahri, Alistar, Amumu, Anivia`,
                answertype: "TEXT",
                answer: "Aatrox (Manaless)",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 26,
                category: "Imposter",
                points: 200,
                type: "TEXT",
                state: "ACTIVE",
                extra: "Active",
                question: `Diese Champs haben in Arcane mitgespielt:
                  Vi, Ambessa, Ekko, Renata, Heimerdinger`,
                answertype: "TEXT",
                answer: "Renata",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 27,
                category: "Imposter",
                points: 300,
                type: "TEXT",
                state: "ACTIVE",
                extra: "Active",
                question: `Diese Champs haben 10 Skins oder mehr (Default nicht mitgezählt) (Stand:19.04.26): 
                  Malzahar, Nasus, Nidalee, Pyke, Lissandra`,
                answertype: "TEXT",
                answer: "Lissandra (9)",
                finished: false,
                buzzedPlayers: [],
                info: "Malzahar (13), Nasus (13), Nidalee (16), Pyke (12), Lissandra (9)",
              },
            ],
            [
              {
                id: 28,
                category: "Imposter",
                points: 400,
                type: "TEXT",
                state: "ACTIVE",
                extra: "Active",
                question: `Diese Champs haben einen Legacy Valentinstag Skin:
                  Rakan, Yuumi, Nami, Annie, Sona`,
                answertype: "TEXT",
                answer: "Nami",
                finished: false,
                buzzedPlayers: [],
                info: "Rakan (Sweetheart), Yuumi (Heartseeker), Nami (keinen), Annie (Sweetheart), Sona (Sweetheart)",
              },
            ],
            [
              {
                id: 29,
                category: "Imposter",
                points: 500,
                type: "TEXT",
                state: "ACTIVE",
                extra: "Active",
                question: `Diese Champs haben einen Attackspeed von mindestens 0,65 (Patch 26.01): 
                  Katarina, Maokai, Sejuani, Xerath, Lucian`,
                answertype: "TEXT",
                answer: "Lucian (0,638)",
                finished: false,
                buzzedPlayers: [],
                info: "Katarina (0,658), Maokai (0,8), Sejuani (0,688), Xerath (0,658), Lucian (0,638)",
              },
            ],
          ],
        },
      ],
    },
    {
      id: 1,
      extra: "default",
      categories: [
        {
          name: "Finanzamt kommt",
          extra: "default",
          questions: [
            [
              {
                id: 0,
                category: "Finanzamt kommt",
                points: 200,
                type: "IMAGE",
                extra: "Active",
                question: "1700_-200.png",
                answertype: "TEXT",
                state: "ACTIVE",
                answer: "1700G",
                finished: false,
                buzzedPlayers: [],
                info: "400 + (2*50) +  1200 = 1700",
              },
            ],
            [
              {
                id: 1,
                category: "Finanzamt kommt",
                points: 400,
                type: "IMAGE",
                extra: "Active",
                question: "4500_-_400.png",
                answertype: "TEXT",
                state: "ACTIVE",
                answer: "4500G",
                finished: false,
                buzzedPlayers: [],
                info: "450 + 3100 + 875 + 75 = 4500",
              },
            ],
            [
              {
                id: 2,
                category: "Finanzamt kommt",
                points: 600,
                type: "IMAGE",
                extra: "Active",
                question: "6850_-_600.png",
                answertype: "TEXT",
                state: "ACTIVE",
                answer: "6850G",
                finished: false,
                buzzedPlayers: [],
                info: "3000 + 1250 + 1200 + 1050 + 350 = 6850",
              },
            ],
            [
              {
                id: 3,
                category: "Finanzamt kommt",
                points: 800,
                type: "IMAGE",
                extra: "Active",
                question: "5030_-_800.png",
                answertype: "TEXT",
                state: "ACTIVE",
                answer: "5030G",
                finished: false,
                buzzedPlayers: [],
                info: "400 + 900 + 600 + 850 + 2200 + (2*40) = 5030",
              },
            ],
            [
              {
                id: 4,
                category: "Finanzamt kommt",
                points: 1000,
                type: "IMAGE",
                extra: "Active",
                question: "2937_-1000.png",
                answertype: "TEXT",
                state: "ACTIVE",
                answer: "2937G",
                finished: false,
                buzzedPlayers: [],
                info: "1337 + 1100 + 150 + 350 = 2937",
              },
            ],
          ],
        },
        {
          name: "Community",
          extra: "default",
          questions: [
            [
              {
                id: 5,
                category: "Community",
                points: 600,
                type: "TEXT",
                state: "ACTIVE",
                extra: "Active",
                question: "Welchen Champ bannst du immer?",
                answertype: "TEXT",
                answer: "Shaco, Mel, Zed",
                finished: false,
                buzzedPlayers: [],
                info: "Shaco: 26, Mel: 16, Zed: 13, Pyke: 12, Fizz: 12, Yasuo: 11, unklar/je nachdem: 10",
              },
            ],
            [
              {
                id: 6,
                category: "Community",
                points: 600,
                type: "TEXT",
                state: "ACTIVE",
                extra: "Active",
                question: "Welchen Champ hast du am liebsten im eigenen Team?",
                answertype: "TEXT",
                answer: "Ornn, Shen, Lulu",
                finished: false,
                buzzedPlayers: [],
                info: "Ornn: 30, Shen: 17, Lulu: 17, Nautilus: 15, Egal/Unklar: 15, Braum: 13, Thresh: 10, Malphite: 10",
              },
            ],
            [
              {
                id: 7,
                category: "Community",
                points: 600,
                type: "TEXT",
                state: "ACTIVE",
                extra: "Active",
                question: "Spielst du mit Flash auf D oder Flash auf F?",
                answertype: "TEXT",
                answer: "D",
                finished: false,
                buzzedPlayers: [],
                info: "Flash auf D: 151, Flash auf F: 141",
              },
            ],
            [
              {
                id: 8,
                category: "Community",
                points: 600,
                type: "TEXT",
                state: "ACTIVE",
                extra: "Active",
                question: "Was ist das beste Emote in League?",
                answertype: "TEXT",
                answer: "OK, Unklar/Keins, Daumen hoch",
                finished: false,
                buzzedPlayers: [],
                info: "OK/'Okay' (Rammus): 114, Unklar/Keins: 40, Daumen hoch/Thumbs Up ('Nice'): 35, Dabbing Pengu (D'Pengu): 21, Bee Happy: 20",
              },
            ],
            [
              {
                id: 9,
                category: "Community",
                points: 600,
                type: "TEXT",
                state: "ACTIVE",
                extra: "Active",
                question:
                  "Was ist dein Lieblingsitem? (was momentan im Shop zu finden ist)",
                answertype: "TEXT",
                answer: "Heartsteel, Rabadons Deathcap, Infinity Edge",
                finished: false,
                buzzedPlayers: [],
                info: "Heartsteel: 26, Rabadons Deathcap: 26, Infinity Edge: 17, Blade of the Ruined King: 15, Shadowflame: 13, Unklar/Keins: 12",
              },
            ],
          ],
        },
        {
          name: "Streamers Liebling",
          extra: "default",
          questions: [
            [
              {
                id: 10,
                category: "Streamers Liebling",
                points: 200,
                type: "VIDEO",
                state: "INVISIBLE",
                extra: "Active",
                question: "BigSpin_Irelia.mp4",
                answertype: "TEXT",
                answer: "Irelia",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 11,
                category: "Streamers Liebling",
                points: 400,
                type: "VIDEO",
                state: "INVISIBLE",
                extra: "Active",
                question: "Mango_Mordekaiser.mp4",
                answertype: "TEXT",
                answer: "Mordekaiser",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 12,
                category: "Streamers Liebling",
                points: 600,
                type: "VIDEO",
                state: "INVISIBLE",
                extra: "Active",
                question: "Mango_Mordekaiser.mp4",
                answertype: "TEXT",
                answer: "5",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 13,
                category: "Streamers Liebling",
                points: 800,
                type: "VIDEO",
                state: "INVISIBLE",
                extra: "Active",
                question: "Mango_Mordekaiser.mp4",
                answertype: "TEXT",
                answer: "5",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 14,
                category: "Streamers Liebling",
                points: 1000,
                type: "VIDEO",
                state: "INVISIBLE",
                extra: "Active",
                question: "Mango_Mordekaiser.mp4",
                answertype: "TEXT",
                answer: "5",
                finished: false,
                buzzedPlayers: [],
              },
            ],
          ],
        },
        {
          name: "OddOneOut",
          extra: "default",
          questions: [
            [
              {
                id: 15,
                category: "OddOneOut",
                points: 200,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "twitch_zaheen_w_auf_r.png",
                answertype: "TEXT",
                answer: "Twitch mit Zaheen W auf R",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 16,
                category: "OddOneOut",
                points: 400,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "rell__skarner_e.png",
                answertype: "TEXT",
                answer: "Rell mit Skarner E auf E",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 17,
                category: "OddOneOut",
                points: 600,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "kassadin__malz_w.png",
                answertype: "TEXT",
                answer: "Kassadin mit Malzahar E auf E",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 18,
                category: "OddOneOut",
                points: 800,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "yasuo__janna_p.png",
                answertype: "TEXT",
                answer: "Yasuo mit Janna Passive auf Passive",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 19,
                category: "OddOneOut",
                points: 1000,
                type: "IMAGE",
                state: "ACTIVE",
                extra: "Active",
                question: "brand__leo_r.png",
                answertype: "TEXT",
                answer: "Brand mit Leona R auf R",
                finished: false,
                buzzedPlayers: [],
              },
            ],
          ],
        },
        {
          name: "Sound Themes",
          extra: "default",
          questions: [
            [
              {
                id: 20,
                category: "Sound Themes",
                points: 200,
                type: "AUDIO",
                state: "INVISIBLE",
                extra: "Active",
                question: "Kaisa.mp3",
                answertype: "TEXT",
                answer: "Kai'sa",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 21,
                category: "Sound Themes",
                points: 400,
                type: "AUDIO",
                state: "INVISIBLE",
                extra: "Active",
                question: "NunuWillump.mp3",
                answertype: "TEXT",
                answer: "Nunu & Willump",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 22,
                category: "Sound Themes",
                points: 600,
                type: "AUDIO",
                state: "INVISIBLE",
                extra: "Active",
                question: "MorgKayle.mp3",
                answertype: "TEXT",
                answer: "Morgana & Kayle",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 23,
                category: "Sound Themes",
                points: 800,
                type: "AUDIO",
                state: "INVISIBLE",
                extra: "Active",
                question: "XayahRakan.mp3",
                answertype: "TEXT",
                answer: "Xayah & Rakan",
                finished: false,
                buzzedPlayers: [],
              },
            ],
            [
              {
                id: 24,
                category: "Sound Themes",
                points: 1000,
                type: "AUDIO",
                state: "INVISIBLE",
                extra: "Active",
                question: "Skarner.mp3",
                answertype: "TEXT",
                answer: "Skarner",
                finished: false,
                buzzedPlayers: [],
              },
            ],
          ],
        },
      ],
    },
  ],
  buzzerQueue: [],
};
